# Generated by Django 4.0.5 on 2022-06-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialect', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
